services:
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "82:80"
    volumes:
      - ./product-service:/var/www/html
    environment:
      - APP_DEBUG=1
      - APP_ENV=dev
      - APP_SECRET=your_secret_here
    networks:
      - product-service-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./user-service:/var/www/html
    environment:
      - APP_DEBUG=1
      - APP_ENV=dev
      - APP_SECRET=your_secret_here
      - DATABASE_URL=mysql://root:userservicepassword@user-database/user_service_db
    networks:
      - product-service-network
      - user-service-network

  user-database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: userservicepassword
      MYSQL_DATABASE: user_service_db
    volumes:
      - user-database-data:/var/lib/mysql
    networks:
      - user-service-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - user-service-network
      - product-service-network

volumes:
  user-database-data:
  redis-data:

networks:
  product-service-network:
  user-service-network:
